### ISSUE TITLE
This script is bot detection free

### ISSUE THREAD

**Issue by Godfatherangle** [phen0menon/blum-autoclicker#14]
I have a question this script is bot detection free or not because Blum recently announced stay away using script or bot , auto clicker if no then can u make human behavior click means if green snowflake come then clickrr start and avoid bomb score like human or something something

**Comment by phen0menon** [comment]
It depends on which bot detection algorithm BLUM engineers use. Looking at the reliability of their applications, I strongly doubt that they have anything that could determine the behavior of my bot :)

Since my bot does not inject anything like Pyrogram sessions or something inside the Telegram application, I don't think it is detectable at all. It's just mouse controller, that's it. 

If you need some numbers, my friends have been using my bot for three and more months across multiple accounts and none of them have been banned.
